name:                mytrie
version:             0.1.0.0
github:              "tchoutri/mytrie"
license:             BSD3
author:              "Théophile Choutri"
maintainer:          "theophile@choutri.eu"
copyright:           "MIT"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/tchoutri/mytrie#readme>

dependencies:
- base                 >= 4.7  && < 5
- bimap                >= 0.4  && < 0.5
- containers           >= 0.6  && < 0.7
- mtl                  >= 2.2  && < 2.3
- text                 >= 1.2  && < 1.3
- unordered-containers >= 0.2  && < 0.3
- vector               >= 0.12 && < 0.13

library:
  source-dirs: src

tests:
  mytrie-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mytrie
